# Generated by Django 6.0 on 2026-01-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_loan_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_fee', 'Pending Fee'), ('fee_paid', 'Fee Paid'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_fee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
