# Generated by Django 6.0 on 2026-01-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
